### ISSUE TITLE
'concurrent' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mounikagudee** [mschwarzmueller/angular-2-beta-boilerplate#30]
I'm getting an issue while "npm start" saying:
'concurrent' is not recognized as an internal or external command,
operable program or batch file.

Below is the error log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\GD1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.2.0
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-boilerplate@1.0.0~prestart: angular2-boilerplate@1.0.0
6 silly lifecycle angular2-boilerplate@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-boilerplate@1.0.0~start: angular2-boilerplate@1.0.0
8 verbose lifecycle angular2-boilerplate@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-boilerplate@1.0.0~start: PATH: C:\Users\GD1\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\GD1\Desktop\angular-2-beta-boilerplate-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jdk1.7.0_51\bin;C:\Program Files\Java\jre7;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon;C:\WINDOWS\system32;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\wamp64\bin\php\php5.6.25;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Google\google_appengine;C:\Users\GD1\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\GD1\AppData\Local\Microsoft\WindowsApps;C:\Users\GD1\AppData\Roaming\Composer\vendor\bin;E:\Program Files\Microsoft VS Code\bin;C:\Users\GD1\AppData\Roaming\npm
10 verbose lifecycle angular2-boilerplate@1.0.0~start: CWD: C:\Users\GD1\Desktop\angular-2-beta-boilerplate-master
11 silly lifecycle angular2-boilerplate@1.0.0~start: Args: [ '/d /s /c', 'concurrent "npm run gulp" "npm run lite" ' ]
12 silly lifecycle angular2-boilerplate@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-boilerplate@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-boilerplate@1.0.0 start: `concurrent "npm run gulp" "npm run lite" `
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\GD1\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\GD1\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-boilerplate@1.0.0
16 verbose cwd C:\Users\GD1\Desktop\angular-2-beta-boilerplate-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\GD1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error angular2-boilerplate@1.0.0 start: `concurrent "npm run gulp" "npm run lite" `
23 error Exit status 1
24 error Failed at the angular2-boilerplate@1.0.0 start script 'concurrent "npm run gulp" "npm run lite" '.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the angular2-boilerplate package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     concurrent "npm run gulp" "npm run lite"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs angular2-boilerplate
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls angular2-boilerplate
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by andreaschrist27** [comment]
have same problem

**Comment by gaglage** [comment]
remove dependency in node_modules and install again. It worked for me

**Comment by jhaytaslim** [comment]
yarn install did it

**Comment by 2advancesolutions** [comment]
Just use angular cli and then do new project don't use this project for
setup it's out of date

**Comment by rjoydip-zz** [comment]
Issue solved after `yarn install`

**Comment by ArmAlam** [comment]
Problem solved after running **yarn add concurrently**
